theme: minima
title: Become developer
author: paulina Adams
description: personal project to create my website/Portfolio
I am eager to gain entry into the tech industry into an exciting development team where I can grow and contribute as a valuable team player with strong communication skills and a solutions-focused approach.
